# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/icey/vulkan/Vulkan

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/icey/vulkan/Vulkan

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/icey/vulkan/Vulkan/CMakeFiles /home/icey/vulkan/Vulkan//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/icey/vulkan/Vulkan/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Shaders

# Build rule for target.
Shaders: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Shaders
.PHONY : Shaders

# fast build rule for target.
Shaders/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Shaders.dir/build.make CMakeFiles/Shaders.dir/build
.PHONY : Shaders/fast

#=============================================================================
# Target rules for targets named Main

# Build rule for target.
Main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Main
.PHONY : Main

# fast build rule for target.
Main/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/build
.PHONY : Main/fast

Src/ExtraFunctions.o: Src/ExtraFunctions.cpp.o
.PHONY : Src/ExtraFunctions.o

# target to build an object file
Src/ExtraFunctions.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/Src/ExtraFunctions.cpp.o
.PHONY : Src/ExtraFunctions.cpp.o

Src/ExtraFunctions.i: Src/ExtraFunctions.cpp.i
.PHONY : Src/ExtraFunctions.i

# target to preprocess a source file
Src/ExtraFunctions.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/Src/ExtraFunctions.cpp.i
.PHONY : Src/ExtraFunctions.cpp.i

Src/ExtraFunctions.s: Src/ExtraFunctions.cpp.s
.PHONY : Src/ExtraFunctions.s

# target to generate assembly for a file
Src/ExtraFunctions.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/Src/ExtraFunctions.cpp.s
.PHONY : Src/ExtraFunctions.cpp.s

Src/ValidationLayers.o: Src/ValidationLayers.cpp.o
.PHONY : Src/ValidationLayers.o

# target to build an object file
Src/ValidationLayers.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/Src/ValidationLayers.cpp.o
.PHONY : Src/ValidationLayers.cpp.o

Src/ValidationLayers.i: Src/ValidationLayers.cpp.i
.PHONY : Src/ValidationLayers.i

# target to preprocess a source file
Src/ValidationLayers.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/Src/ValidationLayers.cpp.i
.PHONY : Src/ValidationLayers.cpp.i

Src/ValidationLayers.s: Src/ValidationLayers.cpp.s
.PHONY : Src/ValidationLayers.s

# target to generate assembly for a file
Src/ValidationLayers.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/Src/ValidationLayers.cpp.s
.PHONY : Src/ValidationLayers.cpp.s

Src/camera.o: Src/camera.cpp.o
.PHONY : Src/camera.o

# target to build an object file
Src/camera.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/Src/camera.cpp.o
.PHONY : Src/camera.cpp.o

Src/camera.i: Src/camera.cpp.i
.PHONY : Src/camera.i

# target to preprocess a source file
Src/camera.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/Src/camera.cpp.i
.PHONY : Src/camera.cpp.i

Src/camera.s: Src/camera.cpp.s
.PHONY : Src/camera.s

# target to generate assembly for a file
Src/camera.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/Src/camera.cpp.s
.PHONY : Src/camera.cpp.s

Src/main.o: Src/main.cpp.o
.PHONY : Src/main.o

# target to build an object file
Src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/Src/main.cpp.o
.PHONY : Src/main.cpp.o

Src/main.i: Src/main.cpp.i
.PHONY : Src/main.i

# target to preprocess a source file
Src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/Src/main.cpp.i
.PHONY : Src/main.cpp.i

Src/main.s: Src/main.cpp.s
.PHONY : Src/main.s

# target to generate assembly for a file
Src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/Src/main.cpp.s
.PHONY : Src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Shaders"
	@echo "... Main"
	@echo "... Src/ExtraFunctions.o"
	@echo "... Src/ExtraFunctions.i"
	@echo "... Src/ExtraFunctions.s"
	@echo "... Src/ValidationLayers.o"
	@echo "... Src/ValidationLayers.i"
	@echo "... Src/ValidationLayers.s"
	@echo "... Src/camera.o"
	@echo "... Src/camera.i"
	@echo "... Src/camera.s"
	@echo "... Src/main.o"
	@echo "... Src/main.i"
	@echo "... Src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

